#!/bin/sh
#Download gz file from a URL
mkdir /Users/andyli-org/Desktop/test/error

#navigate to new error directory
cd /Users/andyli-org/Desktop/test/error && \

#Go to URL and download gz file
curl -O https://s3-us-west-1.amazonaws.com/doug-log-test/logs.txt.gz && \

#Open gz file
gunzip logs.txt.gz                && \

#Count and output number of errors
echo "The number of errors are:"
grep -o 'error' logs.txt | wc -l


